### ISSUE TITLE
Compile with musl libc

### ISSUE THREAD

**Issue by kovaszab** [Idein/libdrm_v3d#3]
Hi guys! Thank you for your work with this amazing little device!

I would like to know if there is a possibility to compile this against the musl-libc6 C library. (an implementation of glibc I think?) I would want to use `qmkl-6` on alpine linux but alpine uses the musl C library. Any consequences that might arise doing that?

Thank you for your answer in advance!

**Comment by Terminus-IMRC** [comment]
Thank you for your interest!
AFAIK we're not using glibc-specific calls, so it should be possible.
Please have a try and report to us if something goes odd.

**Comment by kovaszab** [comment]
This compiled relatively easy. I just had to remove `set(CPACK_DEBIAN_PACKAGE_DEPENDS libc6)` from CMakeLists. However  `qmkl6` is more tricky. After removing the dependency checks that would cause errors because of pkg manager(debian <-> alpine) I can get to this far when i run `make`

```
Scanning dependencies of target mem-qmkl6
[ 57%] Building CXX object test/CMakeFiles/mem-qmkl6.dir/mem.cpp.o
[ 59%] Linking CXX executable mem-qmkl6
/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: ../src/libqmkl6.so: undefined reference to `drm_v3d_wait_bo'
/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: ../src/libqmkl6.so: undefined reference to `drm_v3d_mmap_bo'
/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: ../src/libqmkl6.so: undefined reference to `drm_v3d_create_bo'
/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: ../src/libqmkl6.so: undefined reference to `drm_gem_close'
/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: ../src/libqmkl6.so: undefined reference to `drm_v3d_submit_csd'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/mem-qmkl6.dir/build.make:106: test/mem-qmkl6] Error 1
make[1]: *** [CMakeFiles/Makefile2:990: test/CMakeFiles/mem-qmkl6.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

**Comment by Terminus-IMRC** [comment]
Thank you for trying.
Please install `libdrm_v3d` by `make install`.

**Comment by kovaszab** [comment]
Thank you for the fast response!

I did try that but it seems like musl uses different lib and include dirs. 
Could you help me out how could I change the makefile or the cmakelist so cmake installs it to `/usr/lib` and `/usr/include`? Also there is in the error this folder `/usr/lib/gcc/aarch64-alpine-linux-musl/10.2.1/` so the lib dir might be that instead of `/usr/lib`.
Copying the files manually did not resolve it so I assume it also needs linking or whatever it does under the hood.

I know this is very rookie stuff but I couldn't find useful info online, so thank you very much if you can help!

**Comment by kovaszab** [comment]
The reason why I push Alpine so hard, is because on a headless installation, when I run your sgemm example from py-videocore6, numpy performs with 19 Gflop/s. I think it is maybe because numpy loads lots of libraries underneath, and because Alpine runs everything from ram, there is no disk I/O bottleneck.

**Comment by Terminus-IMRC** [comment]
Please run `cmake . -D CMAKE_INSTALL_PREFIX=/path/to/dir/you/want` to change the install prefix.
(Sorry for just guessing -- I'm unable to touch my Pis today).

As for the performance, I think you are wrong -- please run `command time -v python3 sgemm.py` and see how many major faults occur.
If you install `libopenblas-dev` to Raspberry Pi OS, then you'll get almost the same performance as Alpine.

**Comment by kovaszab** [comment]
Here is the output of ```command time``` that I ran on a headless Alpine aarch64 install

```
$ command time -v python3 examples/sgemm.py
==== sgemm example (1024x1024 times 1024x1024) ====
numpy: 0.1188 sec, 18.11 Gflop/s
QPU:   0.5437 sec, 3.955 Gflop/s
Minimum absolute error: 0.0
Maximum absolute error: 0.0003814697265625
Minimum relative error: 0.0
Maximum relative error: 0.13134673237800598
        Command being timed: "python3 examples/sgemm.py"
        User time (seconds): 2.03
        System time (seconds): 0.45
        Percent of CPU this job got: 107%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0m 2.30s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 250448
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 66427
        Voluntary context switches: 13
        Involuntary context switches: 29
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

This is on Raspbian OS lite armhf after `libopenblas-dev` install: 

```
$ command time -v python3 examples/sgemm.py
==== sgemm example (1024x1024 times 1024x1024) ====
numpy: 0.1977 sec, 10.88 Gflop/s
QPU:   0.5474 sec, 3.929 Gflop/s
Minimum absolute error: 0.0
Maximum absolute error: 0.00040435791015625
Minimum relative error: 0.0
Maximum relative error: 0.16618169844150543
        Command being timed: "python3 examples/sgemm.py"
        User time (seconds): 2.12
        System time (seconds): 1.81
        Percent of CPU this job got: 161%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.43
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 58760
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 60767
        Voluntary context switches: 12
        Involuntary context switches: 48
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

I should also mention that I have the equivalent `libopenblas-dev` pkg installed on the Alpine one.

**Comment by Terminus-IMRC** [comment]
Thank you for testing. As you can see, the performance of NumPy's sgemm improves from ~1 Gflop/s to ~11 Gflop/s after installing OpenBLAS to Raspberry Pi OS armhf. However, it does not reach ~18 Gflop/s of Alpine Linux's NumPy, which [uses OpenBLAS by default](https://pkgs.alpinelinux.org/package/edge/community/aarch64/py3-numpy). It is also confirmed that the same can be said for Raspberry Pi OS arm64 (which achieved only ~6 Gflop/s). It may be possible that Alpine's OpenBLAS is somewhat more optimum for the processor. So, as you suggested, it'd be better for us to use Alpine Linux for CPU-intensive NumPy tasks.

As for the linking issue, it turned out that the linking order of the test programs was incorrect. You now have two choices to fix this:

- Disable building tests by: `cmake -D BUILD_TESTING=FALSE ...`
- Use our updated branch: [Idein/qmkl6:fix-link-order](https://github.com/Idein/qmkl6/tree/fix-link-order)

Can you try either of two and report back?

**Comment by kovaszab** [comment]
Sorry for the late reply!
Checked the branch and now all seems to be ok. I also tried to use the library and it works as expected!

Thank you very much!

**Comment by Terminus-IMRC** [comment]
Good to hear. Thank you again for your interest and the detailed reports!
